/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct msg {
	char message[100];
};
typedef struct msg msg;

#define MSG_PROG 0x2111ffaf
#define MSG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MSG 1
extern  void * msg_1(msg *, CLIENT *);
extern  void * msg_1_svc(msg *, struct svc_req *);
extern int msg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MSG 1
extern  void * msg_1();
extern  void * msg_1_svc();
extern int msg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg (XDR *, msg*);

#else /* K&R C */
extern bool_t xdr_msg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
