/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg.h"
#include <string.h> 
 
char statement[100]; 
int length;
char *substring;
char secret_code[20]="C00L";  
void
msg_prog_1(char *host)  //program MSG_PROG that we defined in the msg.x file."1" indicates the version number
{
	CLIENT *clnt;  //for storing the name of the host
	void  *result_1; //result returned from the server gets stored here. We don't use this.
	msg  msg_1_arg; //the type def of the struct msg in the .x file

#ifndef	DEBUG
	clnt = clnt_create (host, MSG_PROG, MSG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	} 
#endif	/* DEBUG */
	else
	{
				
		printf("Enter an alpha numeric string \n"); //take an alphanumeric string from the user
		scanf("%[^\n]%*c",statement);
		length=strlen(statement); //get the length of the statement		
		if(strstr(statement,"COOL")!=NULL) //Condition to be checked
			
		{

			strncpy(msg_1_arg.message,statement,length);  //copy the input into the parameter msg_1_arg.message
			msg_1_arg.message[length]='\0';	 //appending an end of the line charecter to the string 
		}
		else
		{
			printf("secret code is not included in input\n");

		}
		
	}

	result_1 = msg_1(&msg_1_arg, clnt); //getting back the result from the server side
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	msg_prog_1 (host);
        exit (0);
}
