/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg.h"
#include<string.h>
#include<stdio.h>
#include<stdlib.h>

int i,j,counter,len;
FILE *fp;

void *
msg_1_svc(msg *argp, struct svc_req *rqstp) //server function which takes parameter from the client and stores in argp->message
{
	static char * result;
	printf("The message received on the server side is %s\n",argp); 
	len=strlen(argp->message);
	fp=fopen("secrets.out","w"); //opening the secrets.out file to write out the message that we just received
	fprintf(fp,"The message received is %s\n" ,argp->message);
	fprintf(fp,"\nThe digits in the string are ");

	for(i=0;i<len;i++)
	{

		if(isdigit(argp->message[i]))	//finding out the number of digits in the string 
		{
			fprintf(fp,"%c",argp->message[i]);			
			counter++;
		}
	}
	fprintf(fp,"\nThe number of digits equals %d\n",counter);
	counter=0; //intializing the counter back to 0
	fclose(fp); //closing the file
	

	return (void *) &result; // not returning any value
}
